FROM alpine:3.9
CMD [ "sh" ]
ADD . /path/inside/docker/container

RUN mkdir /out

VOLUME ["/tmp"]


# RUN echo "hello world" > /out/sort_de_docker.txt

# COPY *.txt /c/Users/Julien/AppData/Local/Temp/

# RUN echo "hello world" > /c/Users/Julien/AppData/Local/Temp/
